---
- hosts: webservers
  become: yes

  vars_files:
    - ../../config.yml
    - vars.yml

  pre_tasks:
    - name: Ensure sudo is installed.
      apt: name=sudo state=present

    - name: Check if the Drupal vhost is already configured.
      stat: path=/etc/nginx/sites-enabled/drupal.conf
      register: drupal_vhost_conf

    - name: Ensure rpcbind is purged (first run only).
      apt: name=rpcbind state=absent purge=yes
      when: drupal_vhost_conf.stat.exists == false

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.nginx, tags: ['nginx'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.munin-node, tags: ['munin-node'] }
    - { role: geerlingguy.nfs, tags: ['nfs'] }
    - { role: ../roles/leds, tags: ['leds'] }

  tasks:
    - include: tasks/extras.yml
    - include: tasks/config.yml
    - include: tasks/nfs.yml
    - include: tasks/led-monitor.yml
