---
# See: https://github.com/geerlingguy/raspberry-pi-dramble/issues/65
- name: Ensure rpcbind is running and enabled if exports are present.
  service:
    name: rpcbind
    state: started
    enabled: yes
  register: rpcbind_enable
  when: nfs_exports|length

# See: https://github.com/geerlingguy/raspberry-pi-dramble/issues/65
- name: Restart NFS immediately if exports are updated.
  service: "name={{ nfs_server_daemon }} state=restarted"
  when: rpcbind_enable.changed

- name: Ensure NFS share and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: www-data
    mode: 0775
  with_items:
    - "{{ nfs_share_dir }}"
    - "{{ nfs_mount_dir }}"

- name: Flush handlers so NFS mounts are exported.
  meta: flush_handlers

# Mount configuration.
- name: Ensure the NFS volume is mounted.
  mount:
    name: "{{ nfs_mount_dir }}"
    src: "{{ kubernetes_master_ip }}:{{ nfs_share_dir }}"
    fstype: nfs
    opts: "noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14"
    state: mounted
  when: deploy_target != 'docker'

- name: Ensure extra NFS dirs exist.
  file:
    path: "{{ nfs_mount_dir }}/{{ item }}"
    state: directory
  with_items: "{{ nfs_extra_dirs }}"
  run_once: True
