---
- name: Ensure auth.log file is present.
  file:
    path: /var/log/auth.log
    state: touch
    owner: root
    group: adm
    mode: 0640
  when: deploy_target == 'docker'

- name: Override vars for non-ARM test environments.
  set_fact:
    docker_version: 5:19.03.1~3-0~debian-buster
    mysql_container_image: 'mysql:5.7'
    docker_registry_image: registry:2
    metrics_server_image: k8s.gcr.io/metrics-server-amd64:v0.3.2
    nfs_client_image: quay.io/external_storage/nfs-client-provisioner:latest
  when: deploy_target != 'pi'

- name: Override the drupal_docker_image if it's at its default.
  set_fact:
    drupal_docker_image: geerlingguy/drupal:latest
  when:
    - deploy_target != 'pi'
    - drupal_docker_image == 'geerlingguy/drupal:latest-arm32v7'

- name: Override vars for single-node Docker environment.
  set_fact:
    kubernetes_kubelet_extra_args: '--fail-swap-on=false'
    kubernetes_allow_pods_on_master: True
  when: deploy_target == 'docker'

- name: Override vars for Vagrant environment.
  set_fact:
    kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }}'
  when: deploy_target == 'vagrant'
