---
- name: Ensure /var/www directory exists.
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Ensure drupal_docroot exists.
  file:
    path: "{{ drupal_docroot }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Ensure staging config directory has correct permissions.
  file:
    path: "{{ drupal_docroot }}/sites/default/config/staging"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  when: drupal_install_complete.stat.exists

- name: Download Drupal to the temp folder.
  get_url:
    url: "http://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
    dest: "~/drupal-{{ drupal_version }}.tar.gz"
  register: download_drupal_tarball
  when: drupal_deploy_strategy == 'tarball'

- name: Expand Drupal in the docroot.
  shell: "tar -xf ~/drupal-{{ drupal_version }}.tar.gz --strip 1 -C {{ drupal_docroot }}"
  when: drupal_deploy_strategy == 'tarball' and download_drupal_tarball.changed

- name: Fix permissions on expanded copy of Drupal.
  shell: "chown -R www-data:www-data {{ drupal_docroot }}"
  when: drupal_deploy_strategy == 'tarball' and download_drupal_tarball.changed

- name: Check out Drupal to the docroot.
  git:
    repo: "{{ drupal_repo }}"
    version: "{{ drupal_version }}"
    update: "{{ drupal_keep_updated }}"
    force: yes
    dest: "{{ drupal_docroot }}"
  register: project_updated
  notify: restart nginx
  sudo_user: www-data
  when: drupal_deploy_strategy == 'git'

- name: Copy settings.php file into place.
  template:
    src: ../templates/settings.php.j2
    dest: "{{ drupal_docroot }}/sites/default/settings.php"
    owner: www-data
    group: www-data
  notify: restart nginx

- name: Set permissions on settings.php (pre-install).
  file:
    path: "{{ drupal_docroot }}/sites/default/settings.php"
    mode: 0664
  when: not drupal_install_complete.stat.exists

- name: Ensure settings.php has proper permissions.
  file:
    path: "{{ drupal_docroot }}/sites/default/settings.php"
    mode: 0644
  when: drupal_install_complete.stat.exists
