---
- name: Install Drupal.
  command: >
    drush si {{ drupal_install_profile }} -y
    --site-name="{{ site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_password }}
    chdir={{ drupal_docroot }}
  when: "inventory_hostname == groups.webservers[0]"
  sudo_user: www-data

- name: Wait for Drupal to get bootstrapped.
  pause: seconds=5
  when: "inventory_hostname == groups.webservers[0]"

- name: Override the generated site UUID with our own.
  command: >
    drush config-set -y system.site uuid {{ drupal_site_uuid }}
    chdir={{ drupal_docroot }}
  when: "inventory_hostname == groups.webservers[0]"
  sudo_user: www-data

- name: Ensure settings.php has proper permissions.
  file:
    path: "{{ drupal_docroot }}/sites/default/settings.php"
    mode: 0644

- name: Indicate Drupal has been installed.
  file: path=/var/local/drupal_install_complete state=touch mode=0644
