---
- hosts: database
  become: yes

  vars_files:
    - vars.yml
    - ../../config.yml

  pre_tasks:
    - name: Ensure dependencies are installed.
      apt: name={{ item }} state=present
      with_items:
        - sudo
        - openssh-server

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.munin-node, tags: ['munin-node'] }
    - { role: ../roles/leds, tags: ['leds'] }

  tasks:
    - name: Set the GPIO LED to Green.
      shell: "/usr/bin/rgb green"
      when: deploy_target == 'pi'
