---
firewall_allowed_tcp_ports:
  - 22

# Limit access to MySQL port (3306) to webservers and database servers.
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 3306 -s {{ groups.webservers[0] }} -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3306 -s {{ groups.webservers[1] }} -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3306 -s {{ groups.database[0] }} -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3306 -s {{ groups.database[1] }} -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 4949 -s {{ groups.balancer[0] }} -j ACCEPT"

mysql_root_password: supersecure
mysql_users:
  - name: drupal
    host: "%"
    password: supersecure
    priv: "drupal.*:ALL"

mysql_databases:
  - name: drupal
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1

mysql_bind_address: "{{ ansible_all_ipv4_addresses[0] }}"

# Memory settings.
mysql_key_buffer_size: "32M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_thread_cache_size: "25"
mysql_query_cache_size: "16M"

# InnoDB settings.
mysql_innodb_file_per_table: "1"
mysql_innodb_additional_mem_pool_size: "20M"
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "2"

# Replication settings.
mysql_replication_master: "{{ groups.database[0] }}"
mysql_replication_user:
  name: replication
  password: supersecure

# Munin settings.
munin_node_allowed_ips:
  - "^{{ groups.balancer[0] | replace('.', '\\.') }}$"
