---
- src: geerlingguy.firewall
- src: geerlingguy.nginx
- src: geerlingguy.mysql
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.composer
- src: geerlingguy.drush
- src: geerlingguy.git
- src: geerlingguy.munin
- src: geerlingguy.munin-node
- src: geerlingguy.nfs
- src: geerlingguy.security
