---
- hosts: webservers
  sudo: yes

  vars_files:
    - ../vars.yml
    - vars/main.yml

  pre_tasks:
    - name: Indicate Ansible is deploying to the server.
      command: /usr/bin/rgb red
      changed_when: false
      when: deploy_target == 'pi'

  tasks:
    - name: Check if Drupal has already been installed.
      stat: path=/var/local/drupal_install_complete
      register: drupal_install_complete

    - include: tasks/deploy.yml

    - include: tasks/files.yml

    - include: tasks/install.yml
      when: not drupal_install_complete.stat.exists

    - include: tasks/update.yml
      when: drupal_install_complete.stat.exists and project_updated.changed

    - include: tasks/cron.yml

    - name: Indicate Ansible is finished deploying to the server.
      command: /usr/bin/rgb green
      changed_when: false
      when: deploy_target == 'pi'

  handlers:
    - include: handlers/main.yml
