---
- hosts: balancer
  become: yes

  vars_files:
    - ../../config.yml
    - vars.yml

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.nginx, tags: ['nginx'] }
    - { role: geerlingguy.munin, tags: ['munin'] }
    - { role: ../roles/leds, tags: ['leds'] }

  tasks:
    - include: git-repo.yml
    - include: led-monitor.yml

    - name: Copy vhost configuration into place.
      template:
        src: balancer.conf.j2
        dest: /etc/nginx/sites-enabled/balancer.conf
        mode: 0644
      notify: restart nginx
