---
firewall_allowed_tcp_ports:
  - 22
  - 80

# Nginx configuration.
nginx_default_release: wheezy-backports # For Nginx 1.6.x instead of 1.2.x.
nginx_worker_processes: "4" # Set to number of CPU cores on Pi.
nginx_worker_connections: "1024"
nginx_keepalive_timeout: "1"
nginx_keepalive_requests: "1000"
nginx_proxy_cache_path: "/var/cache/nginx keys_zone=cache:32m max_size=1g inactive=15m"
nginx_remove_default_vhost: true
nginx_vhosts: []
nginx_upstreams:
  - {
    name: dramble,
    # Options: 'least_conn', 'ip_hash' (if not set, round-robin will be used).
    # strategy: "",
    servers: "{{ groups.webservers }}"
  }

# Munin configuration.
munin_admin_user: admin
munin_admin_password: secret
munin_cron_job: absent
munin_hosts:
  - { name: "dramble;bal1.pidramble.com", address: "127.0.0.1", extra: [] }
  - { name: "dramble;www1.pidramble.com", address: "{{ groups.webservers[0] }}", extra: [] }
  - { name: "dramble;www2.pidramble.com", address: "{{ groups.webservers[1] }}", extra: [] }
  - { name: "dramble;www3.pidramble.com", address: "{{ groups.webservers[2] }}", extra: [] }
  - { name: "dramble;www4.pidramble.com", address: "{{ groups.webservers[3] }}", extra: [] }
  - { name: "dramble;db1.pidramble.com", address: "{{ groups.database[0] }}", extra: [] }
